<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GameCore\GameCore.csproj" />
		<ProjectReference Include="..\Log\LogView.csproj" />
		<ProjectReference Include="..\DockerClient\Client.csproj" />
	</ItemGroup>

</Project>
