<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameCore\GameCore.csproj" />
    <ProjectReference Include="..\Log\LogView.csproj" />
    <ProjectReference Include="..\Network\Network.csproj" />
  </ItemGroup>

</Project>
